//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public decimal id_history { get; set; }
        public Nullable<decimal> readers_id { get; set; }
        public Nullable<decimal> book_id { get; set; }
        public string state { get; set; }
    
        public virtual books books { get; set; }
        public virtual readers readers { get; set; }
    }
}
