//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library2022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEntities1 : DbContext
    {

        private static libraryEntities1 context;

        public static libraryEntities1 GetContext()
        {
            if (context == null)
                context = new libraryEntities1();

            return context;
        }
        public libraryEntities1()
            : base("name=libraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<readers> readers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
