//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public decimal id_user { get; set; }
        public string fio { get; set; }
        public string login_user { get; set; }
        public string password_user { get; set; }
    }
}
